# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: peselgen
      MYSQL_ROOT_PASSWORD: q1w2e3r4
    ports:
      - 33069:3306
    volumes:
      - rdm-db:/var/lib/mysql      
  web:
    restart: always
    build: .    
    volumes:
      - .:/code
    ports:
    - "8090:8090" 
    depends_on:
      - db
volumes:
   rdm-db: