version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: peselgen
            MYSQL_ROOT_PASSWORD: q1w2e3r4
            MYSQL_TCP_PORT: 33069
    steps:
      - checkout
      - run:
          name: Waiting for mysql
          command: |
                  for i in `seq 1 60`;
                  do
                    nc -z localhost 33069 && echo Success && exit 0
                    echo -n
                    sleep 1
                  done
                  echo Failed wiating for mysql && exit 1


      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test --settings=peselgen.settings-dev
      - store_artifacts:
          path: test-reports/
          destination: python_app
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys
      - run: ssh-keyscan -H sarian.me >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh deploy@sarian.me "cd /home/sarian/rdm-services && git pull && docker-compose up --force-recreate --build -d"
             
workflows:
  staging:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
